### ISSUE TITLE
DescriptorMap does not have path_nested property

### ISSUE THREAD

**Issue by vpilkevych-ddy** [eu-digital-identity-wallet/eudi-lib-ios-presentation-exchange-swift#28]
It seems that DescriptorMap is missing the required property - path_nested. Please see: https://openid.net/specs/openid-4-verifiable-presentations-1_0-20.html#section-6.1-12

**Comment by dtsiflit** [comment]
Thanks @vpilkevych-ddy we will have a look at this on our end.

**Comment by dtsiflit** [comment]
I have an update for you @vpilkevych-ddy . At this point, our focus is shifting towards [DCQL](https://openid.net/specs/openid-4-verifiable-presentations-1_0.html#name-examples-for-dcql-queries), a JSON-encoded query language that allows Verifiers to request Verifiable Presentations matching specific criteria. As we explore DCQL, we won’t be actively contributing to this library for the time being.

That said, we’re always open to reviewing and accepting contributions from the community. If you have any PRs or suggestions, we’d be happy to take a look.

**Comment by vpilkevych-ddy** [comment]
@dtsiflit good to know and thank you for the bug fix!

**Comment by vpilkevych-ddy** [comment]
@dtsiflit is there any DCQL matcher implementation by any chance?

**Comment by dtsiflit** [comment]
@vpilkevych-ddy not in the immediate future but I will let you know here if that changes!
